name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda: ["download"]
    env:
      SLICE: ${{ matrix.lambda }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvmrc

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvmrc.outputs.NODE_VERSION }}"
          registry-url: "https://npm.pkg.github.com"
          scope: "@lessonnine"

      - name: Install dependencies
        run: npm ci

      - name: Create build
        run: npm run build --workspace=lambdas/$SLICE

      - name: Post build
        run: npm run postbuild --workspace=lambdas/$SLICE

      - name: Deploy to AWS
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ matrix.lambda }}
          zip_file: lambdas/${{ matrix.lambda }}/dist/index.zip
